version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    volumes:                           
      - mariadb:/var/lib/mysql
    build:
      context: requirements/mariadb    
      dockerfile: Dockerfile          
    env_file: .env                     
    restart: always
    ports:
      - "3306:3306"
    networks:          
      - inception

  nginx:
    image: nginx
    container_name: nginx
    volumes:                           
      - wordpress:/var/www/html
    build:
      context: requirements/nginx    
      dockerfile: Dockerfile 
    depends_on:
      - wordpress         
    env_file: .env
    restart: always
    ports:
      - "443:443"                   
    networks:          
      - inception

  wordpress:
    image: wordpress
    container_name: wordpress
    volumes:                           
      - wordpress:/var/www/html
    build:
      context: requirements/wordpress    
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    env_file: .env                  
    restart: always
    expose:
      - "9000"
    networks:          
      - inception

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: '/home/avassor/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
        type: bind
        o: bind
        device: '/home/avassor/data/mariadb'

networks:
  inception:
    driver: bridge