CREATE DATABASE IF NOT EXISTS ${MDBDATABASE};
USE ${MDBDATABASE};
FLUSH PRIVILEGES;
GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY '${MDBROOTPASSWORD}';
ALTER USER 'root'@'%' IDENTIFIED BY '${MDBROOTPASSWORD}';
CREATE USER IF NOT EXISTS '${MDBUSER}'@'%' IDENTIFIED BY '${MDBPASSWORD}';
GRANT ALL PRIVILEGES ON ${MDBDATABASE}.* TO '${MDBUSER}'@'%';
FLUSH PRIVILEGES;